version: '3.7'
services:
  user-service-test:
    restart: on-failure
    depends_on:
    - user-service
    build: .
    container_name: user-service-test
    entrypoint: /test
    environment:
      RUST_LOG: "info"
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  user-service:
    restart: on-failure
    depends_on:
    - dynamodb-local
    build: .
    container_name: user-service
    ports:
    - "8080:8080"
    environment:
      RUST_LOG: "info"
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'