version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  user-service:
    restart: on-failure
    depends_on:
    - dynamodb-local
    build: .
    image: 439000603071.dkr.ecr.us-east-2.amazonaws.com/user-service
    container_name: user-service
    ports:
    - "8080:8080"
    environment:
      RUST_LOG: "debug"
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'